export const autoCompleteOptions = [
    { label: 'Myanmar (MMK)', value: 'MMK' },
    { label: 'United States (USD)', value: 'USD' },
    { label: 'Japan (JPY)', value: 'JPY' },
    { label: 'Germany (EUR)', value: 'EUR' },
    { label: 'United Kingdom (GBP)', value: 'GBP' },
    { label: 'China (CNY)', value: 'CNY' },
    { label: 'India (INR)', value: 'INR' },
    { label: 'Brazil (BRL)', value: 'BRL' },
    { label: 'Canada (CAD)', value: 'CAD' },
    { label: 'Australia (AUD)', value: 'AUD' },
    { label: 'Russia (RUB)', value: 'RUB' },
    // Add more countries as needed
    { label: 'South Korea (KRW)', value: 'KRW' },
    { label: 'Mexico (MXN)', value: 'MXN' },
    { label: 'Indonesia (IDR)', value: 'IDR' },
    { label: 'Turkey (TRY)', value: 'TRY' },
    { label: 'Italy (EUR)', value: 'EUR' },
    { label: 'France (EUR)', value: 'EUR' },
    { label: 'Spain (EUR)', value: 'EUR' },
    { label: 'Netherlands (EUR)', value: 'EUR' },
    { label: 'Switzerland (CHF)', value: 'CHF' },
    { label: 'Saudi Arabia (SAR)', value: 'SAR' },
    { label: 'Argentina (ARS)', value: 'ARS' },
    { label: 'Sweden (SEK)', value: 'SEK' },
    { label: 'Belgium (EUR)', value: 'EUR' },
    { label: 'Poland (PLN)', value: 'PLN' },
    { label: 'Norway (NOK)', value: 'NOK' },
    { label: 'Austria (EUR)', value: 'EUR' },
    { label: 'Iran (IRR)', value: 'IRR' },
    { label: 'South Africa (ZAR)', value: 'ZAR' },
    { label: 'Thailand (THB)', value: 'THB' },
    { label: 'United Arab Emirates (AED)', value: 'AED' },
    { label: 'Malaysia (MYR)', value: 'MYR' },
    { label: 'Nigeria (NGN)', value: 'NGN' },
    { label: 'Israel (ILS)', value: 'ILS' },
    { label: 'Singapore (SGD)', value: 'SGD' },
    { label: 'Hong Kong (HKD)', value: 'HKD' },
    { label: 'Denmark (DKK)', value: 'DKK' },
    { label: 'Philippines (PHP)', value: 'PHP' },
    { label: 'Egypt (EGP)', value: 'EGP' },
    { label: 'Colombia (COP)', value: 'COP' },
    { label: 'Pakistan (PKR)', value: 'PKR' },
    { label: 'Bangladesh (BDT)', value: 'BDT' },
    { label: 'Vietnam (VND)', value: 'VND' },
    { label: 'Chile (CLP)', value: 'CLP' },
    { label: 'Czech Republic (CZK)', value: 'CZK' },
    { label: 'Romania (RON)', value: 'RON' },
    { label: 'Peru (PEN)', value: 'PEN' },
    { label: 'Iraq (IQD)', value: 'IQD' },
    { label: 'Greece (EUR)', value: 'EUR' },
]

// You can now use the autoCompleteOptions array in your application.
